"""Interactively annotate episodes from a synthetic session."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
LAB_ROOT = REPOSITORY_ROOT / "python"
if str(LAB_ROOT) not in sys.path:
    sys.path.insert(0, str(LAB_ROOT))

from eu_digital_lab.annotation import annotate_session  # noqa: E402
from eu_digital_lab.sandbox import read_session  # noqa: E402


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="session JSON generated by generate_sandbox_corpus.py")
    parser.add_argument("output", type=Path, help="annotation JSON output")
    parser.add_argument("--annotator-id", required=True)
    args = parser.parse_args()

    session = read_session(str(args.input))
    answers: dict[str, dict[str, object]] = {}
    for episode in session.episodes:
        print(f"Episode {episode.episode_id} ({episode.routine})")
        label = input("Label: ").strip()
        goal = input("Goal/context (optional): ").strip() or None
        relevance_text = input("Relevance 0..1 (optional): ").strip()
        relevance = float(relevance_text) if relevance_text else None
        answers[episode.episode_id] = {"label": label, "goal": goal, "relevance": relevance}

    result = annotate_session(session, answers, annotator_id=args.annotator_id)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote annotations to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
