"""Deterministic research-lab primitives for the Eu Digital sandbox."""

from .capabilities import (
    CapabilityDescriptor,
    CapabilityRegistry,
    CapabilityRuntime,
    CapabilityState,
    ModuleLifecycleManager,
    PluginDiscovery,
)
from .dialogue_avatar import (
    AvatarPresenter,
    AvatarState,
    AvatarViewState,
    DialogueAvatarController,
    DialogueAvatarError,
    DialogueFeedback,
    DialogueNotice,
    FeedbackAction,
)
from .digital_proprioception_agency import (
    ABLATION as AGENCY_ABLATION,
)
from .digital_proprioception_agency import (
    AGENCY_POLICY_ID,
    ActionIntention,
    AgencyActionOutcome,
    AgencyAttribution,
    AgencyPolicy,
    AttributionLabel,
    DigitalAgencyEngine,
    DigitalAgencyError,
    DigitalBodyState,
    EfferenceCopy,
    macro_f1,
    prediction_error,
)
from .digital_proprioception_agency import (
    BASELINE_POLICY_ID as AGENCY_BASELINE_POLICY_ID,
)
from .digital_proprioception_agency import (
    FALSIFICATION as AGENCY_FALSIFICATION,
)
from .digital_proprioception_agency import (
    HYPOTHESIS as AGENCY_HYPOTHESIS,
)
from .episode_segmentation import (
    BoundaryDecision,
    SegmentationError,
    SegmentationResult,
    SegmentConfig,
    SegmentedEpisode,
    boundary_metrics,
    evaluate_baseline,
    segment_events,
)
from .episodic_memory import (
    EpisodicMemory,
    EpisodicMemoryError,
    MemoryQuery,
    RetrievalResult,
    StoreResult,
)
from .evaluation import (
    DatasetRepository,
    ExperimentConfig,
    ExperimentReport,
    ExperimentRunner,
)
from .functional_self_model import (
    AssertionClassification,
    CapabilityEntry,
    CapabilityStatus,
    DecisionPolicy,
    FunctionalSelfModelError,
    FunctionalSelfModelSnapshot,
    SelfModelAssertion,
    SelfModelDecision,
    SelfModelEvent,
    SelfModelEventKind,
    VersionedFunctionalSelfModel,
)
from .global_workspace import (
    GlobalWorkspace,
    WorkspaceCandidate,
    WorkspaceConfig,
    WorkspaceError,
    WorkspaceItem,
    WorkspaceSnapshot,
    evaluate_selection,
)
from .local_model_gateway import (
    GatewayConfig,
    InvalidModelResponseError,
    LocalModelBackend,
    LocalModelGateway,
    ModelGatewayCancelledError,
    ModelGatewayError,
    ModelGatewayTimeoutError,
    ModelRequest,
    ModelResponse,
    PromptTemplate,
    SchedulingPolicy,
)
from .longitudinal_evaluation import (
    BASELINE_POLICY_ID as LONGITUDINAL_BASELINE_POLICY_ID,
)
from .longitudinal_evaluation import (
    LongitudinalEvaluationError,
    LongitudinalEvaluator,
    LongitudinalProtocol,
    LongitudinalReport,
    LongitudinalSnapshot,
)
from .memory_consolidation import (
    ABLATION as CONSOLIDATION_ABLATION,
)
from .memory_consolidation import (
    BASELINE_POLICY_ID as CONSOLIDATION_BASELINE_POLICY_ID,
)
from .memory_consolidation import (
    CONSOLIDATION_POLICY_ID,
    ConsolidationPolicy,
    ConsolidationRecord,
    MemoryConsolidationError,
    MemoryConsolidator,
    RetentionDecision,
    SemanticKnowledge,
)
from .memory_consolidation import (
    FALSIFICATION as CONSOLIDATION_FALSIFICATION,
)
from .memory_consolidation import (
    HYPOTHESIS as CONSOLIDATION_HYPOTHESIS,
)
from .metacognition_curiosity import (
    CuriosityConfig,
    CuriosityQuestion,
    CuriosityResponse,
    HypothesisRecord,
    HypothesisStatus,
    MetacognitionCuriosityEngine,
    MetacognitionCuriosityError,
    MetacognitiveAssessment,
    QuestionPolicy,
    QuestionStatus,
    ResponseOutcome,
)
from .promotion import PromotionManifest, PromotionPipeline, PromotionRegistry
from .sandbox import SyntheticSession, generate_session, split_sessions
from .validation import ValidationGateRunner, ValidationProtocol
from .world_model import (
    ABLATION as WORLD_MODEL_ABLATION,
)
from .world_model import (
    FALSIFICATION as WORLD_MODEL_FALSIFICATION,
)
from .world_model import (
    FREQUENCY_BASELINE_ID,
    MARKOV_BASELINE_ID,
    PREDICTOR_POLICY_ID,
    DriftSignal,
    ModelPolicy,
    Prediction,
    PredictionConfig,
    WorldModel,
    WorldModelError,
    prediction_error_to_salience,
)
from .world_model import (
    HYPOTHESIS as WORLD_MODEL_HYPOTHESIS,
)

__all__ = [
    "AGENCY_ABLATION",
    "AGENCY_BASELINE_POLICY_ID",
    "AGENCY_FALSIFICATION",
    "AGENCY_HYPOTHESIS",
    "AGENCY_POLICY_ID",
    "CONSOLIDATION_ABLATION",
    "CONSOLIDATION_BASELINE_POLICY_ID",
    "CONSOLIDATION_FALSIFICATION",
    "CONSOLIDATION_HYPOTHESIS",
    "CONSOLIDATION_POLICY_ID",
    "FREQUENCY_BASELINE_ID",
    "LONGITUDINAL_BASELINE_POLICY_ID",
    "MARKOV_BASELINE_ID",
    "PREDICTOR_POLICY_ID",
    "WORLD_MODEL_ABLATION",
    "WORLD_MODEL_FALSIFICATION",
    "WORLD_MODEL_HYPOTHESIS",
    "ActionIntention",
    "AgencyActionOutcome",
    "AgencyAttribution",
    "AgencyPolicy",
    "AssertionClassification",
    "AttributionLabel",
    "AvatarPresenter",
    "AvatarState",
    "AvatarViewState",
    "BoundaryDecision",
    "CapabilityDescriptor",
    "CapabilityEntry",
    "CapabilityRegistry",
    "CapabilityRuntime",
    "CapabilityState",
    "CapabilityStatus",
    "ConsolidationPolicy",
    "ConsolidationRecord",
    "CuriosityConfig",
    "CuriosityQuestion",
    "CuriosityResponse",
    "DatasetRepository",
    "DecisionPolicy",
    "DialogueAvatarController",
    "DialogueAvatarError",
    "DialogueFeedback",
    "DialogueNotice",
    "DigitalAgencyEngine",
    "DigitalAgencyError",
    "DigitalBodyState",
    "DriftSignal",
    "EfferenceCopy",
    "EpisodicMemory",
    "EpisodicMemoryError",
    "ExperimentConfig",
    "ExperimentReport",
    "ExperimentRunner",
    "FeedbackAction",
    "FunctionalSelfModelError",
    "FunctionalSelfModelSnapshot",
    "GatewayConfig",
    "GlobalWorkspace",
    "HypothesisRecord",
    "HypothesisStatus",
    "InvalidModelResponseError",
    "LocalModelBackend",
    "LocalModelGateway",
    "LongitudinalEvaluationError",
    "LongitudinalEvaluator",
    "LongitudinalProtocol",
    "LongitudinalReport",
    "LongitudinalSnapshot",
    "MemoryConsolidationError",
    "MemoryConsolidator",
    "MemoryQuery",
    "MetacognitionCuriosityEngine",
    "MetacognitionCuriosityError",
    "MetacognitiveAssessment",
    "ModelGatewayCancelledError",
    "ModelGatewayError",
    "ModelGatewayTimeoutError",
    "ModelPolicy",
    "ModelRequest",
    "ModelResponse",
    "ModuleLifecycleManager",
    "PluginDiscovery",
    "Prediction",
    "PredictionConfig",
    "PromotionManifest",
    "PromotionPipeline",
    "PromotionRegistry",
    "PromptTemplate",
    "QuestionPolicy",
    "QuestionStatus",
    "ResponseOutcome",
    "RetentionDecision",
    "RetrievalResult",
    "SchedulingPolicy",
    "SegmentConfig",
    "SegmentationError",
    "SegmentationResult",
    "SegmentedEpisode",
    "SelfModelAssertion",
    "SelfModelDecision",
    "SelfModelEvent",
    "SelfModelEventKind",
    "SemanticKnowledge",
    "StoreResult",
    "SyntheticSession",
    "ValidationGateRunner",
    "ValidationProtocol",
    "VersionedFunctionalSelfModel",
    "WorkspaceCandidate",
    "WorkspaceConfig",
    "WorkspaceError",
    "WorkspaceItem",
    "WorkspaceSnapshot",
    "WorldModel",
    "WorldModelError",
    "boundary_metrics",
    "evaluate_baseline",
    "evaluate_selection",
    "generate_session",
    "macro_f1",
    "prediction_error",
    "prediction_error_to_salience",
    "segment_events",
    "split_sessions",
]
