"""Deterministic research-lab primitives for the Eu Digital sandbox."""

from .capabilities import (
    CapabilityDescriptor,
    CapabilityRegistry,
    CapabilityRuntime,
    CapabilityState,
    ModuleLifecycleManager,
    PluginDiscovery,
)
from .episode_segmentation import (
    BoundaryDecision,
    SegmentationError,
    SegmentationResult,
    SegmentConfig,
    SegmentedEpisode,
    boundary_metrics,
    evaluate_baseline,
    segment_events,
)
from .episodic_memory import (
    EpisodicMemory,
    EpisodicMemoryError,
    MemoryQuery,
    RetrievalResult,
    StoreResult,
)
from .evaluation import (
    DatasetRepository,
    ExperimentConfig,
    ExperimentReport,
    ExperimentRunner,
)
from .functional_self_model import (
    AssertionClassification,
    CapabilityEntry,
    CapabilityStatus,
    DecisionPolicy,
    FunctionalSelfModelError,
    FunctionalSelfModelSnapshot,
    SelfModelAssertion,
    SelfModelDecision,
    SelfModelEvent,
    SelfModelEventKind,
    VersionedFunctionalSelfModel,
)
from .global_workspace import (
    GlobalWorkspace,
    WorkspaceCandidate,
    WorkspaceConfig,
    WorkspaceError,
    WorkspaceItem,
    WorkspaceSnapshot,
    evaluate_selection,
)
from .local_model_gateway import (
    GatewayConfig,
    InvalidModelResponseError,
    LocalModelBackend,
    LocalModelGateway,
    ModelGatewayCancelledError,
    ModelGatewayError,
    ModelGatewayTimeoutError,
    ModelRequest,
    ModelResponse,
    PromptTemplate,
    SchedulingPolicy,
)
from .metacognition_curiosity import (
    CuriosityConfig,
    CuriosityQuestion,
    CuriosityResponse,
    HypothesisRecord,
    HypothesisStatus,
    MetacognitionCuriosityEngine,
    MetacognitionCuriosityError,
    MetacognitiveAssessment,
    QuestionPolicy,
    QuestionStatus,
    ResponseOutcome,
)
from .promotion import PromotionManifest, PromotionPipeline, PromotionRegistry
from .sandbox import SyntheticSession, generate_session, split_sessions
from .validation import ValidationGateRunner, ValidationProtocol

__all__ = [
    "AssertionClassification",
    "BoundaryDecision",
    "CapabilityDescriptor",
    "CapabilityEntry",
    "CapabilityRegistry",
    "CapabilityRuntime",
    "CapabilityState",
    "CapabilityStatus",
    "CuriosityConfig",
    "CuriosityQuestion",
    "CuriosityResponse",
    "DatasetRepository",
    "DecisionPolicy",
    "EpisodicMemory",
    "EpisodicMemoryError",
    "ExperimentConfig",
    "ExperimentReport",
    "ExperimentRunner",
    "FunctionalSelfModelError",
    "FunctionalSelfModelSnapshot",
    "GatewayConfig",
    "GlobalWorkspace",
    "HypothesisRecord",
    "HypothesisStatus",
    "InvalidModelResponseError",
    "LocalModelBackend",
    "LocalModelGateway",
    "MemoryQuery",
    "MetacognitionCuriosityEngine",
    "MetacognitionCuriosityError",
    "MetacognitiveAssessment",
    "ModelGatewayCancelledError",
    "ModelGatewayError",
    "ModelGatewayTimeoutError",
    "ModelRequest",
    "ModelResponse",
    "ModuleLifecycleManager",
    "PluginDiscovery",
    "PromotionManifest",
    "PromotionPipeline",
    "PromotionRegistry",
    "PromptTemplate",
    "QuestionPolicy",
    "QuestionStatus",
    "ResponseOutcome",
    "RetrievalResult",
    "SchedulingPolicy",
    "SegmentConfig",
    "SegmentationError",
    "SegmentationResult",
    "SegmentedEpisode",
    "SelfModelAssertion",
    "SelfModelDecision",
    "SelfModelEvent",
    "SelfModelEventKind",
    "StoreResult",
    "SyntheticSession",
    "ValidationGateRunner",
    "ValidationProtocol",
    "VersionedFunctionalSelfModel",
    "WorkspaceCandidate",
    "WorkspaceConfig",
    "WorkspaceError",
    "WorkspaceItem",
    "WorkspaceSnapshot",
    "boundary_metrics",
    "evaluate_baseline",
    "evaluate_selection",
    "generate_session",
    "segment_events",
    "split_sessions",
]
